name: Feature Request
description: Suggest a new feature or enhancement for Azure Command Tower
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help shape the future of Azure Command Tower.
        
        **Note**: Azure Command Tower is in alpha stage. We're actively working on core features, so your suggestions are especially valuable.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other approaches did you think about?

  - type: textarea
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of azct does this feature relate to?
      placeholder: e.g., Navigation/UI, Resource Management, Storage Explorer, Authentication, Performance, Documentation, etc.
    validations:
      required: true

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing functionality?
      options:
        - label: This feature may require breaking changes
          required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be helpful.
      placeholder: Describe how you would use this feature...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our contribution guidelines.
      options:
        - label: I have read and agree to follow the project's contributing guidelines
          required: true
